/**
 * Story text data for all 4 cinematic sequences.
 * Lines can include {color:text} markup for dramatic highlighting.
 * Colors: gold, cyan, purple, red, white (default)
 */

export const STORY_PROLOGUE = {
    voicePath: 'assets/audio/voice/prologue_voice.mp3',
    lines: [
        'Nicht jede Ersch\u00FCtterung',
        'beginnt mit einem Knall...',
        '',
        '{purple:Manche beginnen leise...}',
        '',
        'wie ein Schatten,',
        'der \u00FCber die Sterne gleitet...',
        '',
        '{cyan:Die Dimensionen drifteten auseinander.}',
        'Ideologien verh\u00E4rteten sich...',
        'Licht wurde gehortet,',
        'als sei es Besitz...',
        '',
        'Und irgendwo zwischen',
        'Sternen und Schatten',
        '{gold:stand ein Junge,}',
        'der noch nicht wusste,',
        'dass sein Name einmal',
        'durch Welten getragen',
        'werden w\u00FCrde...',
        '',
        'Und dass wahre St\u00E4rke',
        'nicht im Beherrschen liegt \u2014',
        '{cyan:sondern im Verbinden.}',
    ],
};

export const STORY_REFLEXION = {
    voicePath: 'assets/audio/voice/reflexion_voice.mp3',
    lines: [
        'Die Arenen sind durchschritten...',
        '',
        'Die Vertreter gefallen \u2014',
        'nicht als Besiegte,',
        '{cyan:sondern als Offenbarte.}',
        '',
        '{gold:Keano trat in jede Dimension}',
        'als Fremder.',
        '{cyan:Er verlie\u00DF sie als Spiegel.}',
        '',
        'Denn was er bek\u00E4mpfte,',
        'war nie nur Dunkelheit...',
        '{red:Es war die Angst}',
        '{red:vor Ver\u00E4nderung...}',
        'die Furcht,',
        'Kontrolle zu verlieren...',
        'der Irrglaube,',
        'dass Isolation St\u00E4rke sei...',
        '',
        '{cyan:Jede Welt trug}',
        '{cyan:ihr eigenes Licht...}',
        'doch sie hielten es fest,',
        'als w\u00E4re es endlich...',
        '',
        '{gold:Keano verstand etwas,}',
        'das nur wenige begreifen...',
        '{gold:Licht wird schw\u00E4cher,}',
        '{gold:wenn man es einsperrt...}',
        '',
        'Manche Dimensionen',
        'werden sich wieder setzen...',
        'Manche fallen',
        'wieder in Schatten...',
        '',
        '{cyan:Doch nun existiert ein Weg...}',
        'ein Pfad zwischen den Welten...',
        'ge\u00F6ffnet von einem Jungen',
        'von vierzehn Wintern...',
        'der sich weigerte,',
        'Zersplitterung als Schicksal',
        'zu akzeptieren...',
        '',
        'Solange Dimensionen treiben...',
        'solange Macht',
        '\u00FCber Mitgef\u00FChl gestellt wird...',
        '{gold:wird es jemanden brauchen,}',
        '{gold:der in die Mitte tritt}',
        '{gold:und leuchtet...}',
        '',
        'Und dennoch:',
        '{purple:unersch\u00FCtterlich...}',
    ],
};

export const STORY_EPILOGUE = {
    voicePath: 'assets/audio/voice/epilogue_voice.mp3',
    lines: [
        'Der letzte Gegner',
        'war kein Fremder...',
        '{gold:Er war sein Vater.}',
        '',
        '{cyan:Vikingo \u2014 H\u00FCter der Lichtlinie,}',
        'Vater zweier S\u00F6hne:',
        'Keano, der das Licht trug...',
        'und Jayden, der das Feuer trug...',
        '',
        '{red:Zu lange hatte Vikingo}',
        '{red:in den Abgrund geblickt...}',
        'und der Abgrund blickte zur\u00FCck...',
        'Die Dunkelheit fra\u00DF sein Licht...',
        '',
        'Doch Keano schlug nicht zu,',
        'um zu zerst\u00F6ren...',
        '{cyan:Er schlug zu,}',
        '{cyan:um zu befreien...}',
        '',
        '{gold:Jeder Schlag war ein Ruf:}',
        '{cyan:\u201EKomm zur\u00FCck ins Licht...\u201C}',
        '',
        'Die Linie seiner Ahnen',
        'lehrte ihn:',
        '{gold:Energie darf nicht}',
        '{gold:blockiert werden...}',
        '{cyan:Sie muss flie\u00DFen.}',
        '',
        '{gold:Keano verband}',
        '{gold:das alte Feuer...}',
        'Und die Galaxie',
        'atmete wieder...',
        '',
        'Sanft...',
        'Leise...',
        '{purple:Und dennoch unersch\u00FCtterlich...}',
    ],
};

export const STORY_OUTRO = {
    voicePath: 'assets/audio/voice/outro_voice.mp3',
    lines: [
        'Der Kampf endete...',
        '',
        'nicht mit Vernichtung...',
        '{gold:sondern mit Erinnerung...}',
        '',
        'Das Licht war nicht',
        'st\u00E4rker geworden...',
        '{cyan:Es war wieder im Fluss...}',
        '',
        'Und in diesem Fluss',
        '{gold:lag Hoffnung...}',
        '',
        'Leise...',
        '{purple:doch unverg\u00E4nglich...}',
    ],
};

export const STORY_BIRTHDAY = {
    voicePath: '', // Plays music seamlessly
    lines: [
        '\uD83C\uDF82 {gold:HAPPY BIRTHDAY KEANO} \uD83C\uDF82',
        '\uD83C\uDFC6 {gold:LORD OF THE LIGHT!} \uD83C\uDFC6',
        '\uD83C\uDF87',
        '{cyan:Ein Lichtkristall wurde dir freigeschaltet \u2013}',
        'ein Geschenk des Lords of the Light selbst.',
        'Mit diesem Kristall kannst du',
        'epische Icons f\u00FCr deinen Avatar erwerben.',
        'Er kann nur vom Lord of the Light',
        'genutzt werden und muss bei deinem Vater',
        'eingel\u00F6st werden bis zum n\u00E4chsten Lichtmond,',
        '{cyan:am 28. Februar 2027.}',
        '',
        '{gold:M\u00F6ge dein Licht hell brennen}',
        '{gold:und jede Dimension erleuchten,}',
        '{gold:die du betrittst.}',
        '',
        'In Liebe, Papa \u2764\uFE0F',
        '{purple:KEANO ROMEO - LORD OF THE LIGHT}',
        '\u00A9 2026',
    ],
};
